### ISSUE TITLE
Sign change in Camion's algorithm not applied to (internal) transposed matrix.

### ISSUE THREAD

**Issue by mel-koch** [discopt/cmr#10]
Hello,

I found some matrices that were not camion-signed after the "cmr-convert-matrix -c command". 
I had to use the command a second time so that the matrices were camion-signed. (Sometimes even a third time.)

Here is an example:
7 13
1 0 1 0 1 0 0 1 0 0 0 0 0
0 1 1 0 0 1 0 0 0 1 0 0 1
0 0 0 1 1 1 0 0 0 1 0 0 0
0 0 0 0 0 0 1 1 0 0 0 0 1
0 0 0 0 0 0 0 0 1 1 0 0 1
0 0 0 0 0 0 0 0 0 0 1 0 1
0 0 0 0 0 0 0 0 0 0 0 1 1

After one time of using "cmr-convert-matrix -c":
7 13
1 0 1 0 1 0 0 1 0 0 0 0 0
0 1 1 0 0 1 0 0 0 1 0 0 -1
0 0 0 1 1 -1 0 0 0 -1 0 0 0
0 0 0 0 0 0 1 1 0 0 0 0 1
0 0 0 0 0 0 0 0 1 1 0 0 1
0 0 0 0 0 0 0 0 0 0 1 0 1
0 0 0 0 0 0 0 0 0 0 0 1 1

After two times of using "cmr-convert-matrix -c":
7 13
1 0 1 0 1 0 0 1 0 0 0 0 0
0 1 1 0 0 1 0 0 0 1 0 0 -1
0 0 0 1 1 -1 0 0 0 -1 0 0 0
0 0 0 0 0 0 1 1 0 0 0 0 1
0 0 0 0 0 0 0 0 1 -1 0 0 1
0 0 0 0 0 0 0 0 0 0 1 0 1
0 0 0 0 0 0 0 0 0 0 0 1 1

**Comment by discopt** [comment]
I can confirm that. Intuitively, running `cmr-convert-matrix -c` twice should give the same result. I couldn't track it down, yet, but this is a smaller example:
```
4 4
  
1 1 0 0
1 0 1 1
0 1 1 0
0 0 1 1
```

**Comment by discopt** [comment]
The issue should now be fixed in the master branch. Thank's a lot for reporting it!
