### ISSUE TITLE
Compiler warnings for graphic.c

### ISSUE THREAD

**Issue by rolfvdhulst** [discopt/cmr#14]
I get many many compiler warnings when compiling graphic.c with the highest level of warnings etc. enabled. 
Most crucial cases:

Typenames (so also structs) with a prefixed underscore should be changed: Any type with a underscore is reserved for the standard library (see [here](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier)). For example, _PathEdge should be changed.

Various integer conversion potential bugs,  particularly from size_t -> int  these are narrowing conversions and because signed integer overflow is undefined behavior. These may be implemented differently on different platforms and compilers if you do not add a cast. (For example, in the function addColumnCheck, line 3424, this can happen).

Clang-tidy is also suggesting me to change many function arguments from T * or T[] to const T  or const T[], but this is not really an issue but more of a 'nice' thing. Const correctness can help the compiler to make better optimizations in some cases.

**Comment by discopt** [comment]
I fixed a couple of signing issues in the C code.
