### ISSUE TITLE
Add option in cmake lists for building tests

### ISSUE THREAD

**Issue by rolfvdhulst** [discopt/cmr#18]
Users should not need to compile the tests (particularly with gtest installation being a pain) when installing the library.
This should be a small change to increase QOL. (I have a private branch, but no push rights so I cannot make a PR for this).

**Comment by discopt** [comment]
@rolfvdhulst Could you please try out #19?

**Comment by rolfvdhulst** [comment]
I think you misunderstood me; I was implying something simple along the lines of #21

**Comment by discopt** [comment]
I agree. I merged #21.
