### ISSUE TITLE
`cmr/dec.h` API cannot distinguish `CMR_DEC_IRREGULAR`, `CMR_DEC_UNKNOWN`, `CMR_DEC_SERIES_PARALLEL`

### ISSUE THREAD

**Issue by mkoeppe** [discopt/cmr#32]
Needed for https://github.com/mkoeppe/sage/blob/cmr/src/sage/matrix/seymour_decomposition.pyx#L291

**Comment by discopt** [comment]
I guess you mean that there should be CMRdec* functions that indicates whether, e.g., we have a series-parallel node?!

**Comment by mkoeppe** [comment]
Yes
