### ISSUE TITLE
Consider replacing `CMRmatroiddec{Rows,Columns}Parent` by `CMRmatroiddecChild{Rows,Columns}ToParent`

### ISSUE THREAD

**Issue by mkoeppe** [discopt/cmr#71]
This would be
```
    CMR_ELEMENT* CMRmatroiddecChildRowsToParent(CMR_MATROID_DEC* dec, size_t childIndex)
    CMR_ELEMENT* CMRmatroiddecChildColumnsToParent(CMR_MATROID_DEC* dec, size_t childIndex)
```
and could go along with corresponding changes in `struct _CMR_MATROID_DEC`: 
- Remove `CMR_ELEMENT *rowsParent, *columnsParent` 
- Also remove `struct _CMR_MATROID_DEC* parent` (it's almost unused)
- Instead, add `CMR_ELEMENT **childRowsToParent, **childColumnsToParent` 

This would enable structure sharing, e.g. for a 100-fold 1-sum of the same matrix

**Comment by discopt** [comment]
You mean to keep a mapping from node's rows/columns to that of the parent, but do not store it with the node but with the parent.

**Comment by mkoeppe** [comment]
Yes, exactly.

**Comment by discopt** [comment]
Since the purpose would be to decouple a subtree from the remaining tree, would it make sense to introduce reference counted memory management for decomposition nodes?

**Comment by mkoeppe** [comment]
Yes, that would make sense!
